### PR TITLE
added disclaimer toast for issue 14

### PR DESCRIPTION
**Pull request by KennaReed**
I just added a little disclaimer toast that sensors are theoretical. I had to pull the toast code all the way out to index.js which felt weird, but that was the only way to have it only display on page loads. 

Let me know if anyone has any questions, or if you need me to change anything!

### CODE REVIEW

**Comment by dgaiero** [comment]
Code looks good.

Can you change the toast contents to **All sensor installations are theoretical.** (unless you like the other wording better).

And, is it possible to change the font of the toast to Nunito Sans? It's the same on that is used for the other text on the page.

**Review by dgaiero — CHANGES_REQUESTED** [review]
See comments.

**Comment by KennaReed** [comment]
I changed the toast text to your recommendation above. I spent some time looking into changing the font of the toast text, but the methods I found were not working. This PR also includes the code to handle issue 17 that makes the graph less confusing. I can change the colors and labels pretty easily, so let me know if you want those modified.

**Review by dgaiero — APPROVED** [review]
looks good!

**Pull request merged**
